# Generated by Django 3.0.6 on 2020-05-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
        ('Person', '0002_person_person_is_del'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_project',
            field=models.ManyToManyField(to='Project.Project'),
        ),
    ]
