# Generated by Django 3.0.6 on 2020-05-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_is_del',
            field=models.BooleanField(default=False),
        ),
    ]
